### ISSUE TITLE
Update Kamus

### ISSUE THREAD

**Issue by BoboiAzumi** [IMPHNEN/kamus-gen-z-api#2]
Siapa yang mau buat ini ?

**Comment by dxtstd** [comment]
lagi enggan ngoding

**Comment by Famozzy** [comment]
malas

**Comment by suryami62** [comment]
Ini kerjaan aku 7cff277bdae55e4c81a27f3b73d776951ee07133 . Dan tolong di cek betuk karena aku tak pandai JS.
