### ISSUE TITLE
Read Kamus

### ISSUE THREAD

**Issue by BoboiAzumi** [IMPHNEN/kamus-gen-z-api#3]
Ezz inimah, siapa yang mau buatin ?

**Comment by suryami62** [comment]
napa gak situ aja yg buat kalau EZ :v

**Comment by BoboiAzumi** [comment]
Malas, mending ngurusin unit testing sama nyelipin linter
mhehehehe

**Comment by HengkerKucing** [comment]
maaf nanya bang model databasenya ada yang udah buat belum ya?
